# Generated by Django 2.0.1 on 2018-01-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='_list',
            new_name='belong_to',
        ),
    ]
